services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    restart: always
    depends_on:
      - redis

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - '4000:4000'
    depends_on:
      - upload-service
    environment:
      - UPLOAD_SERVICE_URL=upload-service:50051
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - /app/apps/api-gateway/node_modules # 🚫 Prevent node_modules from overwriting
      - ./uploads:/app/uploads

  upload-service:
    build:
      context: .
      dockerfile: ./apps/upload-service/Dockerfile
    container_name: upload-service
    ports:
      - '50051:50051'
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./apps/upload-service:/app/apps/upload-service
      - /app/apps/upload-service/node_modules # 🚫 Prevent node_modules from overwriting
      - ./uploads:/app/uploads
    # Remove node_modules volume and local mount

  transcoding-service:
    build:
      context: .
      dockerfile: ./apps/transcoding-service/Dockerfile
    container_name: transcoding-service
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./apps/transcoding-service:/app/apps/transcoding-service
      - /app/apps/transcoding-service/node_modules
      - ./uploads:/app/uploads
    # Remove node_modules volume and local mount

  streaming-service:
    build:
      context: .
      dockerfile: ./apps/streaming-service/Dockerfile
    container_name: streaming-service
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./apps/streaming-service:/app/apps/streaming-service
      - /app/apps/streaming-service/node_modules
      - ./uploads:/app/uploads
    # Remove node_modules volume and local mount
