name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.7.0 # Your required version

      - name: Verify pnpm Installation
        run: pnpm --version # Should output 10.7.0

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
